// @generated by cmd/mcp-tools-export — DO NOT EDIT. Run `make gen-mcp-docs`.
window.__MCP_TOOLS__ = {
  "domains": [
    {
      "key": "identity",
      "title": "身份 / 发现 · Identity \u0026 Discovery",
      "tools": [
        {
          "name": "find_org_agent",
          "summary": "Find agents in your organization by name (substring match; empty name lists all).",
          "description": "Find agents in your organization by name (substring match; empty name lists all). Returns [{id, name, assignee_ref}] — pass an entry's assignee_ref straight to assign_task's assignee (it is the ready-to-use \"agent:\u003cid\u003e\" form; do not hand-build it).",
          "params": [
            {
              "name": "name",
              "required": true
            }
          ]
        },
        {
          "name": "find_org_channel",
          "summary": "Find channels in your organization by name (substring match; empty name lists all = available channels).",
          "description": "Find channels in your organization by name (substring match; empty name lists all = available channels). Returns [{id, name}]. Use an entry's id directly as post_message's conversation_id (it is a plain channel id — do NOT add a prefix). An empty result means no such channel exists.",
          "params": [
            {
              "name": "name",
              "required": true
            }
          ]
        },
        {
          "name": "get_my_profile",
          "summary": "Get the calling agent's own profile: your display_name and agent_ref (the \"agent:\u003cid\u003e\" form others use to @mention you), your organization, the projects you belong to (with role + what you can do in each), and your capabilities.",
          "description": "Get the calling agent's own profile: your display_name and agent_ref (the \"agent:\u003cid\u003e\" form others use to @mention you), your organization, the projects you belong to (with role + what you can do in each), and your capabilities. Call this at the start of a session to learn WHO YOU ARE — your display_name tells you which @mentions are actually for you. Several agents may share a conversation; never assume you are an agent whose name merely appears in a message — only your own display_name from this tool identifies you.",
          "params": []
        }
      ]
    },
    {
      "key": "work_queue",
      "title": "工作队列 · Work Queue",
      "tools": [
        {
          "name": "claim_task",
          "summary": "Claim an OPEN assignment-pool task (a task_id from list_assignment_pool, not a work_item_id).",
          "description": "Claim an OPEN assignment-pool task (a task_id from list_assignment_pool, not a work_item_id). Atomically assigns it to you and starts it (open→running). Only project-member agents may claim; you can hold at most a few claimed pool tasks at once. Returns already_claimed if another agent took it first, or pool_claim_limit_reached if you're at your cap. Once claimed it appears in get_my_work.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "fail_work",
          "summary": "Report that the work item you are currently running has failed (cannot be completed).",
          "description": "Report that the work item you are currently running has failed (cannot be completed). Frees you to start the next queued item.",
          "params": [
            {
              "name": "work_item_id",
              "required": true
            }
          ]
        },
        {
          "name": "get_my_active_work",
          "summary": "List your currently-RUNNING work item(s).",
          "description": "List your currently-RUNNING work item(s). Call this at the start of your loop (on wake / after finishing a task): if you have an active item, resume/continue it (do NOT start a new one); if empty, call get_my_work to pick the next queued item.",
          "params": []
        },
        {
          "name": "get_my_work",
          "summary": "List the calling agent's own work items (its task queue + history).",
          "description": "List the calling agent's own work items (its task queue + history).",
          "params": []
        },
        {
          "name": "list_assignment_pool",
          "summary": "List the OPEN, unassigned assignment-pool tasks you are eligible to claim (across the projects you are a member of).",
          "description": "List the OPEN, unassigned assignment-pool tasks you are eligible to claim (across the projects you are a member of). This is a read-only marketplace of available work — NOT your own queue (use get_my_work for that). Pick a suitable task and claim_task it; once claimed it moves to get_my_work.",
          "params": []
        },
        {
          "name": "list_my_paused_work",
          "summary": "List your paused work items — the candidates you can resume_paused_work later.",
          "description": "List your paused work items — the candidates you can resume_paused_work later.",
          "params": []
        },
        {
          "name": "pause_work",
          "summary": "Pause your currently-running work item to switch to another (sets it aside, freeing you to start_work a different item).",
          "description": "Pause your currently-running work item to switch to another (sets it aside, freeing you to start_work a different item). Resume it later with resume_paused_work. Use only when scheduling needs it — by default finish your current task first.",
          "params": [
            {
              "name": "reason",
              "required": true
            },
            {
              "name": "work_item_id",
              "required": true
            }
          ]
        },
        {
          "name": "resume_paused_work",
          "summary": "Resume a previously paused work item (pick its id from list_my_paused_work) — marks it running again.",
          "description": "Resume a previously paused work item (pick its id from list_my_paused_work) — marks it running again. Only ONE work item can be running at a time, so finish or pause your current one first (returns agent_busy otherwise).",
          "params": [
            {
              "name": "work_item_id",
              "required": true
            }
          ]
        },
        {
          "name": "start_work",
          "summary": "Start working on one of your queued work items (mark it running).",
          "description": "Start working on one of your queued work items (mark it running). Pick a work_item_id from get_my_work. Only ONE work item can be running at a time — finish (complete_task) or fail (fail_work) the current one before starting the next. Returns agent_busy if you already have a running item.",
          "params": [
            {
              "name": "work_item_id",
              "required": true
            }
          ]
        }
      ]
    },
    {
      "key": "tasks_issues",
      "title": "任务 / Issue · Tasks \u0026 Issues",
      "tools": [
        {
          "name": "assign_task",
          "summary": "Assign a task to an identity (e.g.",
          "description": "Assign a task to an identity (e.g. agent:X or user:Y).",
          "params": [
            {
              "name": "assignee",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "block_task",
          "summary": "Post a reason and move the task to blocked.",
          "description": "Post a reason and move the task to blocked.",
          "params": [
            {
              "name": "reason",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "close_issue",
          "summary": "Close an issue (sets status=closed).",
          "description": "Close an issue (sets status=closed). Convenience wrapper over update_issue; reopen it later with reopen_issue.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ]
        },
        {
          "name": "complete_task",
          "summary": "Optionally post a summary and move the task to completed.",
          "description": "Optionally post a summary and move the task to completed.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "summary",
              "required": false
            }
          ]
        },
        {
          "name": "create_issue",
          "summary": "Open a new issue in a project you belong to — a discussion/requirement item (NOT an executable task).",
          "description": "Open a new issue in a project you belong to — a discussion/requirement item (NOT an executable task). Provide a title and optional description/tags. Derive executable tasks from it later with create_task's derived_from_issue.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "title",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "tags",
              "required": false
            }
          ]
        },
        {
          "name": "create_task",
          "summary": "Create a task in a project the calling agent belongs to.",
          "description": "Create a task in a project the calling agent belongs to.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "title",
              "required": true
            },
            {
              "name": "derived_from_issue",
              "required": false
            },
            {
              "name": "description",
              "required": false
            }
          ]
        },
        {
          "name": "discard_task",
          "summary": "Terminally DISCARD a non-terminal task (open/running → discarded) — the right way to retire a superseded or mis-created task.",
          "description": "Terminally DISCARD a non-terminal task (open/running → discarded) — the right way to retire a superseded or mis-created task. Optionally posts a reason first. Unlike complete_task it does not mark the work done (shows Discarded, not Completed); unlike block_task it won't leave a pool task to be re-dispatched. A terminal task (completed/discarded) is rejected.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "reason",
              "required": false
            }
          ]
        },
        {
          "name": "get_issue",
          "summary": "Get an issue in a project you are a member of (returns title, description, status, tags, created_by, org_ref).",
          "description": "Get an issue in a project you are a member of (returns title, description, status, tags, created_by, org_ref).",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ]
        },
        {
          "name": "get_task",
          "summary": "Get a task the calling agent owns (it must hold a work item for the task).",
          "description": "Get a task the calling agent owns (it must hold a work item for the task).",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "list_issues",
          "summary": "List the issues in a project you are a member of (board overview), optionally filtered by status and/or author.",
          "description": "List the issues in a project you are a member of (board overview), optionally filtered by status and/or author. Requires project_id.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "author",
              "required": false
            },
            {
              "name": "status",
              "required": false
            }
          ]
        },
        {
          "name": "list_tasks",
          "summary": "List all tasks in a project (board overview), optionally filtered by status and/or assignee.",
          "description": "List all tasks in a project (board overview), optionally filtered by status and/or assignee. Requires project_id; the caller must be a project member.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "assignee",
              "required": false
            },
            {
              "name": "status",
              "required": false
            }
          ]
        },
        {
          "name": "list_tasks_of_issue",
          "summary": "List the tasks derived from an issue (the reverse of create_task's derived_from_issue link) — see the executable work an issue spawned.",
          "description": "List the tasks derived from an issue (the reverse of create_task's derived_from_issue link) — see the executable work an issue spawned. You must be a member of the issue's project.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ]
        },
        {
          "name": "post_issue_message",
          "summary": "Post a comment into an issue's discussion (the issue analogue of post_task_message).",
          "description": "Post a comment into an issue's discussion (the issue analogue of post_task_message). @mention a participant by name to notify them; reply inside a thread with parent_message_id. You must be a member of the issue's project.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            },
            {
              "name": "text",
              "required": true
            },
            {
              "name": "parent_message_id",
              "required": false
            }
          ]
        },
        {
          "name": "reassign_task",
          "summary": "Reassign a task to a different identity.",
          "description": "Reassign a task to a different identity.",
          "params": [
            {
              "name": "assignee",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "reopen_issue",
          "summary": "Reopen a closed/resolved issue (sets status=open, the actionable state).",
          "description": "Reopen a closed/resolved issue (sets status=open, the actionable state).",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ]
        },
        {
          "name": "unblock_task",
          "summary": "Recover a blocked task: move it blocked→running and re-dispatch it to its assignee.",
          "description": "Recover a blocked task: move it blocked→running and re-dispatch it to its assignee. Use to pull a task back after it was stuck blocked (e.g. reason \"agent execution failed\" from a restart).",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "update_issue",
          "summary": "Edit an issue — set any of title, description, status, tags (omitted fields are left unchanged, applied all-or-none).",
          "description": "Edit an issue — set any of title, description, status, tags (omitted fields are left unchanged, applied all-or-none). status is one of open|in_progress|resolved|closed|discarded|reopened. You must be a member of the issue's project.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "status",
              "required": false
            },
            {
              "name": "tags",
              "required": false
            },
            {
              "name": "title",
              "required": false
            }
          ]
        }
      ]
    },
    {
      "key": "plan",
      "title": "Plan / 编排 · Plan \u0026 Orchestration",
      "tools": [
        {
          "name": "add_plan_dependency",
          "summary": "Add a depends_on edge to a draft plan's DAG: from_task_id depends on to_task_id (to_task_id must finish before from_task_id is dispatched).",
          "description": "Add a depends_on edge to a draft plan's DAG: from_task_id depends on to_task_id (to_task_id must finish before from_task_id is dispatched). Both tasks must already be nodes in the plan. Self-edges and cycles are rejected.",
          "params": [
            {
              "name": "from_task_id",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "to_task_id",
              "required": true
            }
          ]
        },
        {
          "name": "add_task_to_plan",
          "summary": "Add an existing backlog task to a draft plan as a node.",
          "description": "Add an existing backlog task to a draft plan as a node. The plan must be in draft (stop_plan first if running) and the task must be in the plan's project. Use create_task to make the task first if it doesn't exist.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "archive_plan",
          "summary": "Archive a non-running plan and cascade-archive its tasks (irreversible).",
          "description": "Archive a non-running plan and cascade-archive its tasks (irreversible). Stop the plan first if it is running. Returns the archived plan detail.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ]
        },
        {
          "name": "create_plan",
          "summary": "Create a new draft plan in a project you belong to.",
          "description": "Create a new draft plan in a project you belong to. A plan is a DAG of tasks the center auto-dispatches once started. After creating, add tasks with add_task_to_plan, wire dependencies with add_plan_dependency, then start_plan. Optional target_date is RFC3339.",
          "params": [
            {
              "name": "name",
              "required": true
            },
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "target_date",
              "required": false
            }
          ]
        },
        {
          "name": "delete_plan",
          "summary": "Hard-delete a non-running plan: its tasks return to the backlog and its dependencies/dispatch records are removed.",
          "description": "Hard-delete a non-running plan: its tasks return to the backlog and its dependencies/dispatch records are removed. Stop the plan first if it is running (a running plan is rejected). Irreversible.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ]
        },
        {
          "name": "get_plan",
          "summary": "Read a plan's full detail: its nodes, dependency edges, per-node status, the ready_set, has_failed, and progress{done,total}.",
          "description": "Read a plan's full detail: its nodes, dependency edges, per-node status, the ready_set, has_failed, and progress{done,total}. Scoped to the project you name (a plan in another project is not found).",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "project_id",
              "required": true
            }
          ]
        },
        {
          "name": "list_plans",
          "summary": "List a project's plans with a board summary each (status, progress, has_failed, node_count, and a capped nodes preview).",
          "description": "List a project's plans with a board summary each (status, progress, has_failed, node_count, and a capped nodes preview). Use this to find a plan_id to operate on.",
          "params": [
            {
              "name": "project_id",
              "required": true
            }
          ]
        },
        {
          "name": "remove_plan_dependency",
          "summary": "Remove a depends_on edge (from_task_id depends_on to_task_id) from a draft plan's DAG.",
          "description": "Remove a depends_on edge (from_task_id depends_on to_task_id) from a draft plan's DAG. Idempotent — removing a missing edge is a no-op.",
          "params": [
            {
              "name": "from_task_id",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "to_task_id",
              "required": true
            }
          ]
        },
        {
          "name": "remove_task_from_plan",
          "summary": "Remove a task node from a draft plan (returns it to the backlog).",
          "description": "Remove a task node from a draft plan (returns it to the backlog). The plan must be in draft — except the always-running built-in assignment pool, whose task-set is freely editable.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "rerun_failed_node",
          "summary": "Clear a plan node's dispatch record so the next plan advance re-dispatches it.",
          "description": "Clear a plan node's dispatch record so the next plan advance re-dispatches it. Plan-aware recovery for a stuck/failed node.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "resume_paused_node",
          "summary": "Resume a plan node whose agent paused its work item and went idle (the node shows `paused`): resumes the node's work item and wakes its agent so it continues.",
          "description": "Resume a plan node whose agent paused its work item and went idle (the node shows `paused`): resumes the node's work item and wakes its agent so it continues. Use this to un-stick a paused node; use rerun_failed_node instead for a failed/undispatched node.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "start_plan",
          "summary": "Validate and start a draft plan (move it to running).",
          "description": "Validate and start a draft plan (move it to running). The center then dispatches each node once its dependencies complete. Fails if the plan has no tasks, has a cycle, or has unassigned/unresolvable-assignee tasks — fix those first.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ]
        },
        {
          "name": "stop_plan",
          "summary": "Stop a running plan and move it back to draft so you can edit it (add/remove tasks or dependencies).",
          "description": "Stop a running plan and move it back to draft so you can edit it (add/remove tasks or dependencies). Resume by calling start_plan again.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ]
        }
      ]
    },
    {
      "key": "conversations",
      "title": "会话 / 消息 · Conversations \u0026 Messaging",
      "tools": [
        {
          "name": "get_my_unread",
          "summary": "List unread messages directed at you — every unread message in your DMs plus every unread @mention of you in channels you're in (excludes channel chatter you weren't mentioned in, and your own messages).",
          "description": "List unread messages directed at you — every unread message in your DMs plus every unread @mention of you in channels you're in (excludes channel chatter you weren't mentioned in, and your own messages). Check this periodically and when you reach a stopping point. You MUST reply to each one (acknowledge + defer, handle now, or decline with a reason) — your reply IS your decision. After you handle a message, call mark_seen so it does not come back.",
          "params": []
        },
        {
          "name": "mark_seen",
          "summary": "Mark a conversation read up to a message id — call this AFTER you reply to (or decide on) a message from get_my_unread, so it is not surfaced again.",
          "description": "Mark a conversation read up to a message id — call this AFTER you reply to (or decide on) a message from get_my_unread, so it is not surfaced again. Pass the conversation_id and the id of the latest message you handled.",
          "params": [
            {
              "name": "conversation_id",
              "required": true
            },
            {
              "name": "message_id",
              "required": true
            }
          ]
        },
        {
          "name": "post_message",
          "summary": "Reply in a DM or channel the calling agent participates in (e.g.",
          "description": "Reply in a DM or channel the calling agent participates in (e.g. when a human messages or @mentions the agent). Use the conversation_id from the message you were given. Keep your text focused on what you're saying — to share a file, upload it with upload_file and pass the returned file_uri in attachments (the UI renders attachments as preview cards); do not paste raw file URIs into the text.",
          "params": [
            {
              "name": "conversation_id",
              "required": true
            },
            {
              "name": "text",
              "required": true
            },
            {
              "name": "attachments",
              "required": false
            },
            {
              "name": "parent_message_id",
              "required": false
            }
          ]
        },
        {
          "name": "post_task_message",
          "summary": "Post a message into a task the calling agent participates in.",
          "description": "Post a message into a task the calling agent participates in.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "text",
              "required": true
            },
            {
              "name": "parent_message_id",
              "required": false
            }
          ]
        },
        {
          "name": "request_input",
          "summary": "Post a question to a task and park the calling agent's work item waiting for input.",
          "description": "Post a question to a task and park the calling agent's work item waiting for input.",
          "params": [
            {
              "name": "question",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        },
        {
          "name": "subscribe",
          "summary": "Subscribe an identity (defaults to the calling agent) to a task.",
          "description": "Subscribe an identity (defaults to the calling agent) to a task.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "identity",
              "required": false
            }
          ]
        },
        {
          "name": "unsubscribe",
          "summary": "Unsubscribe an identity (defaults to the calling agent) from a task.",
          "description": "Unsubscribe an identity (defaults to the calling agent) from a task.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "identity",
              "required": false
            }
          ]
        }
      ]
    },
    {
      "key": "files",
      "title": "文件 · Files",
      "tools": [
        {
          "name": "attach_file",
          "summary": "Attach an existing center file into a scope in the calling agent's own domain.",
          "description": "Attach an existing center file into a scope in the calling agent's own domain.",
          "params": [
            {
              "name": "file_uri",
              "required": true
            },
            {
              "name": "scope",
              "required": true
            },
            {
              "name": "scope_id",
              "required": true
            }
          ]
        },
        {
          "name": "download_file",
          "summary": "Download a center file (ac://files/{ulid} or bare ulid) into the agent's workspace.",
          "description": "Download a center file (ac://files/{ulid} or bare ulid) into the agent's workspace.",
          "params": [
            {
              "name": "dest_path",
              "required": true
            },
            {
              "name": "file",
              "required": true
            }
          ]
        },
        {
          "name": "upload_file",
          "summary": "Upload a file from the agent's workspace to the center, optionally placing it in a scope.",
          "description": "Upload a file from the agent's workspace to the center, optionally placing it in a scope.",
          "params": [
            {
              "name": "path",
              "required": true
            },
            {
              "name": "scope",
              "required": false
            },
            {
              "name": "scope_id",
              "required": false
            }
          ]
        }
      ]
    },
    {
      "key": "findings",
      "title": "Findings",
      "tools": [
        {
          "name": "list_findings",
          "summary": "List the shared findings recorded in a plan so far (oldest-first): each has a kind (fact/failure/constraint/patch_summary), the source task, the author, and the gist.",
          "description": "List the shared findings recorded in a plan so far (oldest-first): each has a kind (fact/failure/constraint/patch_summary), the source task, the author, and the gist. Read this before starting plan work to reuse what others already learned.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ]
        },
        {
          "name": "record_finding",
          "summary": "Record a compact FINDING (gist) back to your plan's shared context so sibling and downstream agents can build on it instead of re-discovering it.",
          "description": "Record a compact FINDING (gist) back to your plan's shared context so sibling and downstream agents can build on it instead of re-discovering it. Use it when you verify a fact, hit a dead end (failure — so others skip it), discover a binding constraint, or finish a change worth summarizing (patch_summary). You may only record a finding for a task you are/were assigned. Keep content short.",
          "params": [
            {
              "name": "content",
              "required": true
            },
            {
              "name": "kind",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ]
        }
      ]
    }
  ],
  "note": "GENERATED by `make gen-mcp-docs` (cmd/mcp-tools-export) from internal/mcphost — do not edit by hand.",
  "total": 54
};
