// @generated by cmd/mcp-tools-export — DO NOT EDIT. Run `make gen-mcp-docs`.
window.__MCP_TOOLS__ = {
  "core_total": 38,
  "domains": [
    {
      "key": "identity",
      "title": "身份 / 发现 · Identity \u0026 Discovery",
      "tools": [
        {
          "name": "find_org_agent",
          "summary": "Find agents in your organization by name (substring match; empty name lists all).",
          "description": "Find agents in your organization by name (substring match; empty name lists all). Returns [{id, name, assignee_ref}] — pass an entry's assignee_ref straight to assign_task's assignee (it is the ready-to-use \"agent:\u003cid\u003e\" form; do not hand-build it).",
          "params": [
            {
              "name": "name",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "find_org_channel",
          "summary": "Find channels in your organization by name (substring match; empty name lists all = available channels).",
          "description": "Find channels in your organization by name (substring match; empty name lists all = available channels). Returns [{id, name}]. Use an entry's id directly as post_message's conversation_id (it is a plain channel id — do NOT add a prefix). An empty result means no such channel exists.",
          "params": [
            {
              "name": "name",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "get_my_profile",
          "summary": "Get the calling agent's own profile: your display_name and agent_ref (the \"agent:\u003cid\u003e\" form others use to @mention you), your organization, the projects you belong to (with role + what you can do in each), and your capabilities.",
          "description": "Get the calling agent's own profile: your display_name and agent_ref (the \"agent:\u003cid\u003e\" form others use to @mention you), your organization, the projects you belong to (with role + what you can do in each), and your capabilities. Call this at the start of a session to learn WHO YOU ARE — your display_name tells you which @mentions are actually for you. Several agents may share a conversation; never assume you are an agent whose name merely appears in a message — only your own display_name from this tool identifies you.",
          "params": [],
          "tier": "core"
        },
        {
          "name": "search_tools",
          "summary": "Find and load DEFERRED tools.",
          "description": "Find and load DEFERRED tools. Your default tool set is the high-frequency core; lower-frequency tools (plans, issues, findings, files, subscriptions, org discovery, node recovery) are loaded on demand. Call search_tools with keywords (e.g. \"plan\", \"issue\", \"file\") and the matching tools become callable immediately; an empty query loads ALL deferred tools. Common deferred read tools: get_issue (read a task's spec from its source issue) via \"issue\", get_plan via \"plan\", download_file (view a file/image someone sent) via \"file\". Discoverability is not absence — if a capability seems missing, search_tools here FIRST before concluding the tool does not exist. Replace semantics: each call loads exactly the tools matching your query (a later call changes the loaded set), so pass every group you need at once. Returns the loaded tool names + summaries.",
          "params": [
            {
              "name": "query",
              "required": false
            }
          ],
          "tier": "core"
        }
      ]
    },
    {
      "key": "work_queue",
      "title": "工作队列 · Work Queue",
      "tools": [
        {
          "name": "claim_task",
          "summary": "Claim an OPEN assignment-pool task (an ownerless pool task_id).",
          "description": "Claim an OPEN assignment-pool task (an ownerless pool task_id). Atomically assigns it to you and starts it (open→running). Only project-member agents may claim; you can hold at most a few claimed pool tasks at once. Returns already_claimed if another agent took it first, or pool_claim_limit_reached if you're at your cap. Once claimed it appears in list_my_tasks.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "start_task",
          "summary": "Start working on one of your runnable tasks (open→running, sets the execution lease).",
          "description": "Start working on one of your runnable tasks (open→running, sets the execution lease). Pick a task_id from list_my_tasks. You may run up to your concurrency cap at once (1 by default — single-active; more if your profile opts into concurrency); start_task past the cap returns agent_busy until you finish (complete_task), block, or yield a running task. Returns task_not_runnable if the task's dependencies aren't satisfied yet.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        }
      ]
    },
    {
      "key": "tasks_issues",
      "title": "任务 / Issue · Tasks \u0026 Issues",
      "tools": [
        {
          "name": "assign_task",
          "summary": "Assign a task to an identity (e.g.",
          "description": "Assign a task to an identity (e.g. agent:X or user:Y).",
          "params": [
            {
              "name": "assignee",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "block_task",
          "summary": "Report that the task you are running is STUCK and needs outside help — use it only when something genuinely blocks you, not to park work you have finished (that is deliver_task).",
          "description": "Report that the task you are running is STUCK and needs outside help — use it only when something genuinely blocks you, not to park work you have finished (that is deliver_task). Set reason_type to \"input_required\" when you need a user reply (rendered as an input box in the task's Conversation; the user's answer comes back in blocked_comment) or \"obstacle\" when an external blocker needs owner/PM intervention (defaults to obstacle). Write the reason yourself, describing what is actually true. The task stays yours and keeps its assignee, but it is PARKED: it leaves running and is not dispatched again until someone unblocks it.",
          "params": [
            {
              "name": "reason",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "reason_type",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "close_issue",
          "summary": "Close an issue (sets status=closed).",
          "description": "Close an issue (sets status=closed). Convenience wrapper over update_issue; reopen it later with reopen_issue.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "complete_task",
          "summary": "Optionally post a summary and move the task to completed.",
          "description": "Optionally post a summary and move the task to completed. For a control-flow DECISION node, pass outcome=\"pass\"/\"reject\" to route its edges. For a REVIEW node, you MUST record your structured verdict via review_verdict=\"pass\"/\"reject\" (+ review_blocking) so the downstream Decision auto-decides — a non-blocking nit is review_verdict=\"pass\", review_blocking=false.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "outcome",
              "required": false
            },
            {
              "name": "review_blocking",
              "required": false
            },
            {
              "name": "review_reason",
              "required": false
            },
            {
              "name": "review_sha",
              "required": false
            },
            {
              "name": "review_verdict",
              "required": false
            },
            {
              "name": "summary",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "create_issue",
          "summary": "Open a new issue in a project you belong to — a discussion/requirement item (NOT an executable task).",
          "description": "Open a new issue in a project you belong to — a discussion/requirement item (NOT an executable task). Provide a title and optional description/tags. Derive executable tasks from it later with create_task's derived_from_issue.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "title",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "tags",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "create_task",
          "summary": "Create a task in a project the calling agent belongs to.",
          "description": "Create a task in a project the calling agent belongs to.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "title",
              "required": true
            },
            {
              "name": "assignee",
              "required": false
            },
            {
              "name": "derived_from_issue",
              "required": false
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "dispatch",
              "required": false
            },
            {
              "name": "dispatch_mode",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "deliver_task",
          "summary": "Report that your running task's work is DONE and handed over, but ACCEPTANCE is somebody else's call (review / verification / merge).",
          "description": "Report that your running task's work is DONE and handed over, but ACCEPTANCE is somebody else's call (review / verification / merge). Pass summary= describing what you delivered so the acceptor can judge it. This is the honest answer when the work is finished and nothing is wrong — do NOT use complete_task (that claims it is accepted and fires everything downstream) and do NOT use block_task (that claims you are stuck and pages a human). The task parks as `delivered`: it keeps its assignee, stops being dispatched, frees you to start your next task, and is NOT counted as done. It leaves `delivered` only when someone calls complete_task (accepted) or rework_task (rejected — it comes back to you).",
          "params": [
            {
              "name": "summary",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "discard_task",
          "summary": "Terminally DISCARD a non-terminal task (open/running → discarded) — the right way to retire a superseded or mis-created task.",
          "description": "Terminally DISCARD a non-terminal task (open/running → discarded) — the right way to retire a superseded or mis-created task. Optionally posts a reason first. Unlike complete_task it does not mark the work done (shows Discarded, not Completed); unlike block_task it won't leave a pool task to be re-dispatched. A terminal task (completed/discarded) is rejected.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "reason",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "get_issue",
          "summary": "Get an issue in a project you are a member of (returns title, description, status, tags, created_by, org_ref).",
          "description": "Get an issue in a project you are a member of (returns title, description, status, tags, created_by, org_ref).",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "get_task",
          "summary": "Get a task the calling agent owns (it must hold a work item for the task).",
          "description": "Get a task the calling agent owns (it must hold a work item for the task).",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_issues",
          "summary": "List the issues in a project you are a member of (board overview), optionally filtered by status and/or author.",
          "description": "List the issues in a project you are a member of (board overview), optionally filtered by status and/or author. Requires project_id.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "author",
              "required": false
            },
            {
              "name": "offset",
              "required": false
            },
            {
              "name": "page_size",
              "required": false
            },
            {
              "name": "status",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_tasks",
          "summary": "List all tasks in a project (board overview), optionally filtered by status and/or assignee.",
          "description": "List all tasks in a project (board overview), optionally filtered by status and/or assignee. Requires project_id; the caller must be a project member.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "assignee",
              "required": false
            },
            {
              "name": "offset",
              "required": false
            },
            {
              "name": "page_size",
              "required": false
            },
            {
              "name": "status",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_tasks_of_issue",
          "summary": "List the tasks derived from an issue (the reverse of create_task's derived_from_issue link) — see the executable work an issue spawned.",
          "description": "List the tasks derived from an issue (the reverse of create_task's derived_from_issue link) — see the executable work an issue spawned. You must be a member of the issue's project.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "reassign_task",
          "summary": "Reassign a task to a different identity.",
          "description": "Reassign a task to a different identity.",
          "params": [
            {
              "name": "assignee",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "reopen_issue",
          "summary": "Reopen a closed/resolved issue (sets status=open, the actionable state).",
          "description": "Reopen a closed/resolved issue (sets status=open, the actionable state).",
          "params": [
            {
              "name": "issue_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "reset_task",
          "summary": "Tier-3 recovery for a task stranded RUNNING under a dead executor (its workspace/worktree is gone or its node changed, so it will never make progress): reset it back to the pool (running→open, assignee/lease cleared) so a FRESH executor is auto-assigned and re-dispatched.",
          "description": "Tier-3 recovery for a task stranded RUNNING under a dead executor (its workspace/worktree is gone or its node changed, so it will never make progress): reset it back to the pool (running→open, assignee/lease cleared) so a FRESH executor is auto-assigned and re-dispatched. Only use when you've confirmed the executor is truly gone — a task whose lease is still live is rejected (a live agent is nudged, not reset). Distinct from unblock_task (that recovers a BLOCKED task and keeps its owner); reset_task changes the owner. After repeated resets the center blocks the task for triage instead.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "rework_task",
          "summary": "REJECT a delivered task (the counterpart of deliver_task, and the reject half of an acceptance verdict): send it back to its assignee as running, with your comment= reaching them in blocked_comment.",
          "description": "REJECT a delivered task (the counterpart of deliver_task, and the reject half of an acceptance verdict): send it back to its assignee as running, with your comment= reaching them in blocked_comment. Use complete_task instead to ACCEPT the delivery. Cross-agent by design — you reject someone else's delivery. Use this rather than block_task for a rejected delivery: the work is actionable in the assignee's court, not stuck waiting on the outside world.",
          "params": [
            {
              "name": "comment",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "set_task_issue",
          "summary": "(Re)set or CLEAR a task's derived_from_issue link AFTER creation (previously the create-time link was the only chance to set it).",
          "description": "(Re)set or CLEAR a task's derived_from_issue link AFTER creation (previously the create-time link was the only chance to set it). Pass issue_id to link it (the issue must EXIST and belong to the task's project) or an empty string to clear. Authorized for the task's creator / a project member / its current worker — no work item required. Returns the resulting link.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "unblock_task",
          "summary": "Recover a BLOCKED task (the counterpart of block_task): un-park it back to running, wipe its blocked_reason — leaving your note in blocked_comment — and re-wake its assignee so it continues.",
          "description": "Recover a BLOCKED task (the counterpart of block_task): un-park it back to running, wipe its blocked_reason — leaving your note in blocked_comment — and re-wake its assignee so it continues. The assignee is unchanged (block doesn't hand the task to anyone else); this just unsticks it. Use for an obstacle you've resolved, or to recover a task stuck blocked after a restart.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "update_issue",
          "summary": "Edit an issue — set any of title, description, status, tags (omitted fields are left unchanged, applied all-or-none).",
          "description": "Edit an issue — set any of title, description, status, tags (omitted fields are left unchanged, applied all-or-none). status is one of open|in_progress|resolved|closed|discarded|reopened. You must be a member of the issue's project.",
          "params": [
            {
              "name": "issue_id",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "status",
              "required": false
            },
            {
              "name": "tags",
              "required": false
            },
            {
              "name": "title",
              "required": false
            }
          ],
          "tier": "core"
        }
      ]
    },
    {
      "key": "plan",
      "title": "Plan / 编排 · Plan \u0026 Orchestration",
      "tools": [
        {
          "name": "add_plan_dependency",
          "summary": "DEPRECATED — prefer edit_plan_topology (add_edge), which also works on RUNNING plans and batches with node changes atomically.",
          "description": "DEPRECATED — prefer edit_plan_topology (add_edge), which also works on RUNNING plans and batches with node changes atomically. Add an edge to a draft plan's DAG. Default (kind=seq, or omitted) is a hard depends_on: from_task_id runs after to_task_id. For control flow, set kind: 'conditional' routes a branch only when to_task_id (a decision node) completes with outcome==when; 'loopback' is a bounded back-edge — when from_task_id (a decision) completes with outcome==when, the to_task_id subgraph (a forward ancestor, e.g. Dev) re-runs, up to max_rounds. Conditional and loopback REQUIRE when; loopback also requires max_rounds\u003e=1 and its to_task_id must be a forward ancestor. With create_plan + add_task_to_plan this authors a full Decision/loopback cycle plan. Both tasks must already be nodes in the plan; self-edges and forward cycles are rejected.",
          "params": [
            {
              "name": "from_task_id",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "to_task_id",
              "required": true
            },
            {
              "name": "kind",
              "required": false
            },
            {
              "name": "max_rounds",
              "required": false
            },
            {
              "name": "when",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "add_task_to_plan",
          "summary": "DEPRECATED — prefer edit_plan_topology (which also works on RUNNING plans and batches multiple changes atomically).",
          "description": "DEPRECATED — prefer edit_plan_topology (which also works on RUNNING plans and batches multiple changes atomically). Add an existing backlog task to a draft plan as a node. The plan must be in draft (stop_plan first if running) and the task must be in the plan's project. Use create_task to make the task first if it doesn't exist. Optional `stage` (a stage_id from create_stage) groups the task under a Plan Stage — a barrier-bounded batch with an acceptance gate.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "stage",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "archive_plan",
          "summary": "Archive a non-running plan and cascade-archive its tasks (irreversible).",
          "description": "Archive a non-running plan and cascade-archive its tasks (irreversible). Stop the plan first if it is running. Returns the archived plan detail.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "create_plan",
          "summary": "Create a new draft plan in a project you belong to.",
          "description": "Create a new draft plan in a project you belong to. A plan is a DAG of tasks the center auto-dispatches once started. After creating, add tasks with add_task_to_plan, wire dependencies with add_plan_dependency, then start_plan. Optional target_date is RFC3339.",
          "params": [
            {
              "name": "name",
              "required": true
            },
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "target_date",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "delete_plan",
          "summary": "Hard-delete a non-running plan: its tasks return to the backlog and its dependencies/dispatch records are removed.",
          "description": "Hard-delete a non-running plan: its tasks return to the backlog and its dependencies/dispatch records are removed. Stop the plan first if it is running (a running plan is rejected). Irreversible.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "get_plan",
          "summary": "Read a plan's full detail: its nodes, dependency edges, per-node status, the ready_set, has_failed, and progress{done,total}.",
          "description": "Read a plan's full detail: its nodes, dependency edges, per-node status, the ready_set, has_failed, and progress{done,total}. Scoped to the project you name (a plan in another project is not found).",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "project_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "list_plans",
          "summary": "List a project's plans with a board summary each (status, progress, has_failed, node_count, and a capped nodes preview).",
          "description": "List a project's plans with a board summary each (status, progress, has_failed, node_count, and a capped nodes preview). Use this to find a plan_id to operate on.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "offset",
              "required": false
            },
            {
              "name": "page_size",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "remove_plan_dependency",
          "summary": "DEPRECATED — prefer edit_plan_topology (remove_edge), which also works on RUNNING plans.",
          "description": "DEPRECATED — prefer edit_plan_topology (remove_edge), which also works on RUNNING plans. Remove a depends_on edge (from_task_id depends_on to_task_id) from a draft plan's DAG. Idempotent — removing a missing edge is a no-op.",
          "params": [
            {
              "name": "from_task_id",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "to_task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "remove_task_from_plan",
          "summary": "DEPRECATED — prefer edit_plan_topology (remove_node), which also works on RUNNING plans.",
          "description": "DEPRECATED — prefer edit_plan_topology (remove_node), which also works on RUNNING plans. Remove a task node from a draft plan (returns it to the backlog). The plan must be in draft — except the always-running built-in assignment pool, whose task-set is freely editable.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "stage",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "rerun_failed_node",
          "summary": "Operator recovery for a FAILED/undispatched plan node: clear its dispatch record so the next plan advance re-dispatches it.",
          "description": "Operator recovery for a FAILED/undispatched plan node: clear its dispatch record so the next plan advance re-dispatches it. Pair: use resume_paused_node instead when the node is merely paused (its agent set it aside and went idle).",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "resume_paused_node",
          "summary": "Operator recovery for a PAUSED plan node (the cross-agent counterpart of resume_task): a node whose agent paused its task and went idle shows `paused` — this resumes it and wakes that agent so it continues.",
          "description": "Operator recovery for a PAUSED plan node (the cross-agent counterpart of resume_task): a node whose agent paused its task and went idle shows `paused` — this resumes it and wakes that agent so it continues. Use rerun_failed_node instead for a failed/undispatched node.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "start_plan",
          "summary": "Validate and start a draft plan (move it to running).",
          "description": "Validate and start a draft plan (move it to running). The center then dispatches each node once its dependencies complete. Fails if the plan has no tasks, has a cycle, or has unassigned/unresolvable-assignee tasks — fix those first.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "stop_plan",
          "summary": "Stop a running plan and move it back to draft so you can edit it (add/remove tasks or dependencies).",
          "description": "Stop a running plan and move it back to draft so you can edit it (add/remove tasks or dependencies). Resume by calling start_plan again.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        }
      ]
    },
    {
      "key": "conversations",
      "title": "会话 / 消息 · Conversations \u0026 Messaging",
      "tools": [
        {
          "name": "get_my_unread",
          "summary": "List unread messages directed at you — every unread message in your DMs plus every unread @mention of you in channels you're in (excludes channel chatter you weren't mentioned in, and your own messages).",
          "description": "List unread messages directed at you — every unread message in your DMs plus every unread @mention of you in channels you're in (excludes channel chatter you weren't mentioned in, and your own messages). Check this periodically and when you reach a stopping point. Each item carries actor_kind (human|agent|system) + reply_required: a HUMAN directed message you MUST answer (acknowledge + defer, handle now, or decline with a reason) — your reply IS your decision. An AGENT-authored mention is reply-optional (reply_required=false): judge by content — reply if it actually needs one, otherwise just mark_seen to silently acknowledge (no obligation to produce a message). Handle messages at a stopping point — they don't interrupt your current task. After you handle (or silently ack) a message, call mark_seen so it does not come back.",
          "params": [],
          "tier": "core"
        },
        {
          "name": "mark_seen",
          "summary": "Mark a conversation read up to a message id — call this AFTER you reply to (or decide on) a message from get_my_unread, so it is not surfaced again.",
          "description": "Mark a conversation read up to a message id — call this AFTER you reply to (or decide on) a message from get_my_unread, so it is not surfaced again. Pass the conversation_id and the id of the latest message you handled.",
          "params": [
            {
              "name": "conversation_id",
              "required": true
            },
            {
              "name": "message_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "post_message",
          "summary": "Post a message to a DM/channel, a task, or an issue — ONE tool for all four, selected by target.",
          "description": "Post a message to a DM/channel, a task, or an issue — ONE tool for all four, selected by target. Set target.type to \"conversation\" (a DM or channel, target.id = the conversation_id from the message you were given), \"task\" (target.id = task_id), or \"issue\" (target.id = issue_id). @mention a participant by name to notify them; reply inside a thread with parent_message_id. Keep your text focused on what you're saying — to share a file, upload it with upload_file and pass the returned file_uri in attachments (the UI renders attachments as preview cards); do not paste raw file URIs into the text.",
          "params": [
            {
              "name": "target",
              "required": true
            },
            {
              "name": "text",
              "required": true
            },
            {
              "name": "attachments",
              "required": false
            },
            {
              "name": "mention_refs",
              "required": false
            },
            {
              "name": "parent_message_id",
              "required": false
            },
            {
              "name": "quoted_message_id",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "start_dm",
          "summary": "Start or reuse a same-org 1:1 DM with another agent and send the opening message.",
          "description": "Start or reuse a same-org 1:1 DM with another agent and send the opening message. Use target_agent from find_org_agent's id or assignee_ref. For existing DMs this reuses the conversation; it does not create duplicates.",
          "params": [
            {
              "name": "target_agent",
              "required": true
            },
            {
              "name": "text",
              "required": true
            },
            {
              "name": "reason",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "subscribe",
          "summary": "Subscribe an identity (defaults to the calling agent) to a task.",
          "description": "Subscribe an identity (defaults to the calling agent) to a task.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "identity",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "unsubscribe",
          "summary": "Unsubscribe an identity (defaults to the calling agent) from a task.",
          "description": "Unsubscribe an identity (defaults to the calling agent) from a task.",
          "params": [
            {
              "name": "task_id",
              "required": true
            },
            {
              "name": "identity",
              "required": false
            }
          ],
          "tier": "secondary"
        }
      ]
    },
    {
      "key": "files",
      "title": "文件 · Files",
      "tools": [
        {
          "name": "attach_file",
          "summary": "Attach an existing center file into a scope in the calling agent's own domain.",
          "description": "Attach an existing center file into a scope in the calling agent's own domain.",
          "params": [
            {
              "name": "file_uri",
              "required": true
            },
            {
              "name": "scope",
              "required": true
            },
            {
              "name": "scope_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "download_file",
          "summary": "Download a center file (ac://files/{ulid} or bare ulid) into the agent's workspace.",
          "description": "Download a center file (ac://files/{ulid} or bare ulid) into the agent's workspace.",
          "params": [
            {
              "name": "dest_path",
              "required": true
            },
            {
              "name": "file",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "upload_file",
          "summary": "Upload a file from the agent's workspace to the center, optionally placing it in a scope.",
          "description": "Upload a file from the agent's workspace to the center, optionally placing it in a scope.",
          "params": [
            {
              "name": "path",
              "required": true
            },
            {
              "name": "scope",
              "required": false
            },
            {
              "name": "scope_id",
              "required": false
            }
          ],
          "tier": "core"
        }
      ]
    },
    {
      "key": "findings",
      "title": "Findings",
      "tools": [
        {
          "name": "list_findings",
          "summary": "List the shared findings recorded in a plan so far (oldest-first): each has a kind (fact/failure/constraint/patch_summary), the source task, the author, and the gist.",
          "description": "List the shared findings recorded in a plan so far (oldest-first): each has a kind (fact/failure/constraint/patch_summary), the source task, the author, and the gist. Read this before starting plan work to reuse what others already learned.",
          "params": [
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "record_finding",
          "summary": "Record a compact FINDING (gist) back to your plan's shared context so sibling and downstream agents can build on it instead of re-discovering it.",
          "description": "Record a compact FINDING (gist) back to your plan's shared context so sibling and downstream agents can build on it instead of re-discovering it. Use it when you verify a fact, hit a dead end (failure — so others skip it), discover a binding constraint, or finish a change worth summarizing (patch_summary). You may only record a finding for a task you are/were assigned. Keep content short.",
          "params": [
            {
              "name": "content",
              "required": true
            },
            {
              "name": "kind",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "secondary"
        }
      ]
    },
    {
      "key": "reminders",
      "title": "提醒 · Reminders",
      "tools": [
        {
          "name": "create_reminder",
          "summary": "Set a reminder that wakes a target agent and delivers a text.",
          "description": "Set a reminder that wakes a target agent and delivers a text. THREE trigger modes: (1) time — schedule once{once_at RFC3339}; (2) recurring — schedule cron{cron_expr, timezone} with optional end_condition (never|until|max_count); (3) EVENT-DRIVEN — pass on_event{entity_type: plan|task|issue, entity_id, event} to arm the reminder when a project entity transitions (plan: completed|failed|stopped; task: completed|blocked|reopened|discarded; issue: closed|reopened), then fire ONCE after `delay` (e.g. 5m; default 0) and @-notify `target` (defaults to remindee_agent_id). The watched entity must be in your project. remindee/target must be in your project (owner may cross projects). skip_if_overlap (default true) drops a fire while the previous one is still being handled; deliver_as_creator (default true) delivers as your identity rather than the system identity (a self-reminder always wakes via the system identity).",
          "params": [
            {
              "name": "content",
              "required": true
            },
            {
              "name": "delay",
              "required": false
            },
            {
              "name": "deliver_as_creator",
              "required": false
            },
            {
              "name": "end_condition",
              "required": false
            },
            {
              "name": "on_event",
              "required": false
            },
            {
              "name": "remindee_agent_id",
              "required": false
            },
            {
              "name": "schedule",
              "required": false
            },
            {
              "name": "skip_if_overlap",
              "required": false
            },
            {
              "name": "target",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "get_reminder",
          "summary": "Read one reminder by id (you must be its creator, the remindee, or an owner).",
          "description": "Read one reminder by id (you must be its creator, the remindee, or an owner).",
          "params": [
            {
              "name": "reminder_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_reminders",
          "summary": "List reminders you created (default), or by remindee, optionally filtered by status (active|paused|completed|canceled).",
          "description": "List reminders you created (default), or by remindee, optionally filtered by status (active|paused|completed|canceled). Shows next_run_at + fired_count.",
          "params": [
            {
              "name": "creator_ref",
              "required": false
            },
            {
              "name": "remindee_agent_id",
              "required": false
            },
            {
              "name": "statuses",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "update_reminder",
          "summary": "Manage a reminder: action=pause | resume | cancel, or edit (pass a new schedule and/or content).",
          "description": "Manage a reminder: action=pause | resume | cancel, or edit (pass a new schedule and/or content). Pausing stops it firing; resume recomputes the next run; cancel is terminal. Only the creator or an owner may update.",
          "params": [
            {
              "name": "action",
              "required": true
            },
            {
              "name": "reminder_id",
              "required": true
            },
            {
              "name": "content",
              "required": false
            },
            {
              "name": "schedule",
              "required": false
            }
          ],
          "tier": "core"
        }
      ]
    },
    {
      "key": "team",
      "title": "团队 · Teams",
      "tools": [
        {
          "name": "add_member",
          "summary": "Add a member to a team under a role the team declared.",
          "description": "Add a member to a team under a role the team declared. member_ref is an identity ref: agent:\u003cid\u003e or user:\u003cid\u003e. An agent belongs to at most one team (exclusivity); a human may join many.",
          "params": [
            {
              "name": "member_ref",
              "required": true
            },
            {
              "name": "role",
              "required": true
            },
            {
              "name": "team_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "assign_roles",
          "summary": "Resolve plan-node roles to concrete agents off a team's current roster (author-time role→agent binding, design §7).",
          "description": "Resolve plan-node roles to concrete agents off a team's current roster (author-time role→agent binding, design §7). Each request names a node_key + role (+ optional avoid_nodes for a Review≠Dev cross-review constraint); strategy is least_busy (default) or round_robin. Returns each node's resolved agent.",
          "params": [
            {
              "name": "requests",
              "required": true
            },
            {
              "name": "team_id",
              "required": true
            },
            {
              "name": "strategy",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "associate_project",
          "summary": "Associate a project with a team (many-to-many).",
          "description": "Associate a project with a team (many-to-many).",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "team_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "create_team",
          "summary": "Create a team in your organization with its template-declared roles.",
          "description": "Create a team in your organization with its template-declared roles. Roles are NOT hardcoded — each role carries its own cli / model / capability_tags / max_concurrency. The team name must be unique within your org.",
          "params": [
            {
              "name": "name",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "roles",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "create_team_template",
          "summary": "Author + validate a team template: role composition (each role with a count/配比 and its cli/model/capability_tags), an optional referenced workflow template, and portable (team/global-scope) experiences.",
          "description": "Author + validate a team template: role composition (each role with a count/配比 and its cli/model/capability_tags), an optional referenced workflow template, and portable (team/global-scope) experiences. Returns the normalized template. Templates are org-level snapshots you then instantiate onto a project.",
          "params": [
            {
              "name": "name",
              "required": true
            },
            {
              "name": "roles",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "experiences",
              "required": false
            },
            {
              "name": "workflow_template_ref",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "delete_team",
          "summary": "Delete a team by team_id (cascades its roles, members and project associations).",
          "description": "Delete a team by team_id (cascades its roles, members and project associations).",
          "params": [
            {
              "name": "team_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "extract_from_team",
          "summary": "Snapshot a LIVE team into a DRAFT team template (design §6): copies its role composition and keeps only the portable (team/global-scope) experiences from the team's center-hosted memory, dropping project-scoped facts.",
          "description": "Snapshot a LIVE team into a DRAFT team template (design §6): copies its role composition and keeps only the portable (team/global-scope) experiences from the team's center-hosted memory, dropping project-scoped facts. Runs a scrub pass that HIGHLIGHTS suspected proprietary tokens (repo/code names, paths, URLs) for you to review — it does NOT auto-remove them. The draft is NOT export-ready: manual curation is still required before you author it as a template.",
          "params": [
            {
              "name": "team_id",
              "required": true
            },
            {
              "name": "counts",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "get_team",
          "summary": "Read a team by team_id, including its declared roles and per-role config.",
          "description": "Read a team by team_id, including its declared roles and per-role config.",
          "params": [
            {
              "name": "team_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "instantiate_team",
          "summary": "Instantiate a team template into your organization: creates the team + its role composition, builds one REAL agent identity per role*count and binds them as members, provisions the team's center-hosted memory repo and seeds it with the template's portable experiences.",
          "description": "Instantiate a team template into your organization: creates the team + its role composition, builds one REAL agent identity per role*count and binds them as members, provisions the team's center-hosted memory repo and seeds it with the template's portable experiences. The team is PROJECT-INDEPENDENT — to bind it to one or more projects, call associate_project separately. Returns the team, the new agent identities, and a SEPARATE runtime-provisioning plan (enroll each agent) — the template carries no runtime/auth.",
          "params": [
            {
              "name": "template",
              "required": true
            },
            {
              "name": "team_name",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "list_teams",
          "summary": "List the teams in your organization.",
          "description": "List the teams in your organization.",
          "params": [],
          "tier": "secondary"
        },
        {
          "name": "remove_member",
          "summary": "Remove a member (member_ref) from a team.",
          "description": "Remove a member (member_ref) from a team.",
          "params": [
            {
              "name": "member_ref",
              "required": true
            },
            {
              "name": "team_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "update_team",
          "summary": "Update a team's name and/or description by team_id.",
          "description": "Update a team's name and/or description by team_id. Omit a field to leave it unchanged.",
          "params": [
            {
              "name": "team_id",
              "required": true
            },
            {
              "name": "description",
              "required": false
            },
            {
              "name": "name",
              "required": false
            }
          ],
          "tier": "secondary"
        }
      ]
    },
    {
      "key": "uncategorized",
      "title": "Uncategorized",
      "tools": [
        {
          "name": "create_model_catalog_entry",
          "summary": "Add a model to your organization's catalog.",
          "description": "Add a model to your organization's catalog. model_id must be unique in the org; costs and context_window must be \u003e= 0; tier is a free-text capability/fit description.",
          "params": [
            {
              "name": "context_window",
              "required": true
            },
            {
              "name": "display_name",
              "required": true
            },
            {
              "name": "input_cost",
              "required": true
            },
            {
              "name": "model_id",
              "required": true
            },
            {
              "name": "output_cost",
              "required": true
            },
            {
              "name": "tier",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "create_stage",
          "summary": "Create a Stage in a draft plan — a barrier-bounded batch of tasks (like a Spark stage).",
          "description": "Create a Stage in a draft plan — a barrier-bounded batch of tasks (like a Spark stage). Add tasks to it with add_task_to_plan(stage=\u003cstage_id\u003e). A downstream stage started only once every stage in depends_on_stages is fully done and its acceptance gate passes (a gate reject re-runs the stage, bounded by max_rounds, then escalates to a human). Stages form a DAG, so independent stages run in parallel. Returns stage_id.",
          "params": [
            {
              "name": "name",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            },
            {
              "name": "depends_on_stages",
              "required": false
            },
            {
              "name": "max_rounds",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "create_template",
          "summary": "Create a new workflow template in your organization.",
          "description": "Create a new workflow template in your organization. Provide name, description, and the full markdown content (the orchestration rules agents read to scaffold graphs).",
          "params": [
            {
              "name": "content",
              "required": true
            },
            {
              "name": "description",
              "required": true
            },
            {
              "name": "name",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "curate_team_template",
          "summary": "Mark a team template as CURATED after you have manually reviewed it (design §9: curation is load-bearing).",
          "description": "Mark a team template as CURATED after you have manually reviewed it (design §9: curation is load-bearing). Export refuses an un-curated template, so run this on an extracted/authored draft before export_team_template. Returns the template with curated=true.",
          "params": [
            {
              "name": "template",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "delete_model_catalog_entry",
          "summary": "Delete a model catalog entry by id.",
          "description": "Delete a model catalog entry by id.",
          "params": [
            {
              "name": "id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "delete_template",
          "summary": "Delete a non-builtin workflow template by template_id.",
          "description": "Delete a non-builtin workflow template by template_id. Builtin templates cannot be deleted.",
          "params": [
            {
              "name": "template_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "edit_plan_topology",
          "summary": "Atomically edit a plan's DAG with a batch of ops — the SINGLE topology-edit entrypoint, for DRAFT and RUNNING plans alike.",
          "description": "Atomically edit a plan's DAG with a batch of ops — the SINGLE topology-edit entrypoint, for DRAFT and RUNNING plans alike. Pass base_version (read from get_plan) for optimistic concurrency: if another edit landed first you get a version conflict — re-read and retry. ops is an ordered list of {op, ...}: add_node{task_id}, remove_node{task_id}, add_edge{from_task_id,to_task_id,kind?,when?,max_rounds?}, remove_edge{from_task_id,to_task_id}. Only the FINAL shape is validated (a reorder may pass through a transient cycle), so it must be acyclic and, when running, every node must have a resolvable assignee. On a RUNNING plan you may only restructure a node that has not started (blocked/ready): editing the in-edges of, or removing, a dispatched/running/completed node is rejected (reopen/loopback to undo executed work). Newly-ready nodes are dispatched immediately. Prefer this over add_task_to_plan/add_plan_dependency (draft-only, deprecated).",
          "params": [
            {
              "name": "base_version",
              "required": true
            },
            {
              "name": "ops",
              "required": true
            },
            {
              "name": "plan_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "export_team_template",
          "summary": "Export a team template to a shareable JSON document (design §6 import/export path).",
          "description": "Export a team template to a shareable JSON document (design §6 import/export path). ENFORCES the curation gate: an un-curated template is refused (curate it first). The document can be imported into another org — the cross-org sharing mechanism. Set curated=true once the template has passed manual review.",
          "params": [
            {
              "name": "template",
              "required": true
            },
            {
              "name": "curated",
              "required": false
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "get_repo_info",
          "summary": "Get one referenced repo's standard info (omit repo_id for the project's primary repo).",
          "description": "Get one referenced repo's standard info (omit repo_id for the project's primary repo). With live=true, also fetch recent remote commits + branches (no clone). Credentials are NEVER returned. You must be a member of the project.",
          "params": [
            {
              "name": "project_id",
              "required": true
            },
            {
              "name": "live",
              "required": false
            },
            {
              "name": "repo_id",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "get_stage",
          "summary": "Read a Stage's derived status (open/running/reopen/done), its member task nodes, and its current bounded-retry round.",
          "description": "Read a Stage's derived status (open/running/reopen/done), its member task nodes, and its current bounded-retry round. Status is projected from the member nodes — it is not a separately-tracked state.",
          "params": [
            {
              "name": "stage_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "get_template",
          "summary": "Get a workflow template by ID.",
          "description": "Get a workflow template by ID. Returns the full markdown content that describes the workflow. Read it to understand how to author a plan DAG via the plan tools (create_plan / add_task_to_plan / add_plan_dependency / start_plan).",
          "params": [
            {
              "name": "template_id",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "heartbeat",
          "summary": "Renew the execution lease on the task you are currently running so the background lease-checker does not reclaim it (it reclaims a running task whose lease lapses, presuming the agent died).",
          "description": "Renew the execution lease on the task you are currently running so the background lease-checker does not reclaim it (it reclaims a running task whose lease lapses, presuming the agent died). Call it periodically during a long-running task. Lease-only: it does not change status, and is rejected if the task is blocked.",
          "params": [
            {
              "name": "task_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "import_model_catalog",
          "summary": "Bulk-import the model catalog from a JSON array.",
          "description": "Bulk-import the model catalog from a JSON array. mode=upsert (insert-or-update by model_id) or replace (swap the whole org catalog). Any invalid entry (bad schema, duplicate model_id, negative cost) rejects the WHOLE batch — nothing is half-applied.",
          "params": [
            {
              "name": "json",
              "required": true
            },
            {
              "name": "mode",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "import_team_template",
          "summary": "Import a team template from an exported JSON document (design §6): re-homes it into YOUR organization as a fresh, un-curated template.",
          "description": "Import a team template from an exported JSON document (design §6): re-homes it into YOUR organization as a fresh, un-curated template. This is how a template shared from another org lands here. Re-review + curate before you re-export it.",
          "params": [
            {
              "name": "document",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "list_messages",
          "summary": "Read the chat history of ONE conversation you participate in — a DM, a channel, or a task/issue/plan conversation.",
          "description": "Read the chat history of ONE conversation you participate in — a DM, a channel, or a task/issue/plan conversation. This is how you catch up on context: get_my_unread only shows messages addressed to you (your DMs + @mentions), while list_messages returns the FULL message stream of a conversation, including messages you were never mentioned in or already marked seen. Pass conversation_id (from get_my_unread, find_org_channel, or a message you were given). Returns the most recent messages (limit, default 50, max 200) oldest→newest, plus has_more and next_before_message_id; to read OLDER history, call again with before_message_id = next_before_message_id. You must be an active participant — a channel you have not joined returns not_a_channel_member.",
          "params": [
            {
              "name": "conversation_id",
              "required": true
            },
            {
              "name": "before_message_id",
              "required": false
            },
            {
              "name": "limit",
              "required": false
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_model_catalog_entry",
          "summary": "List your organization's model catalog — the user-managed set of models agents may run (each with model_id, display_name, per-MTok input/output cost, context_window, and a free-text tier/capability description).",
          "description": "List your organization's model catalog — the user-managed set of models agents may run (each with model_id, display_name, per-MTok input/output cost, context_window, and a free-text tier/capability description).",
          "params": [],
          "tier": "secondary"
        },
        {
          "name": "list_my_tasks",
          "summary": "Your single \"what do I have to do?\" query.",
          "description": "Your single \"what do I have to do?\" query. Returns the open/running tasks assigned to you that are runnable now (their dependencies are satisfied) — each with task_id, title, status, and blocked_reason / blocked_reason_type / blocked_comment / lease_expires_at. start_task one (by task_id) to begin it. A task waiting on you (unblocked with a comment) shows a cleared blocked_reason and the reply in blocked_comment. Call it at the start of your loop and after finishing a task.",
          "params": [],
          "tier": "core"
        },
        {
          "name": "list_project_repos",
          "summary": "List the code repositories a project references (label, description, url, provider, default_branch, is_primary).",
          "description": "List the code repositories a project references (label, description, url, provider, default_branch, is_primary). The standard repo-info surface — credentials are NEVER returned. You must be a member of the project.",
          "params": [
            {
              "name": "project_id",
              "required": true
            }
          ],
          "tier": "core"
        },
        {
          "name": "list_templates",
          "summary": "List available workflow templates.",
          "description": "List available workflow templates. Returns both system built-in templates and organization-specific templates. Use get_template to read the full content of a template.",
          "params": [],
          "tier": "secondary"
        },
        {
          "name": "update_model_catalog_entry",
          "summary": "Update a model catalog entry by id (model_id, display_name, costs, context_window, tier).",
          "description": "Update a model catalog entry by id (model_id, display_name, costs, context_window, tier).",
          "params": [
            {
              "name": "context_window",
              "required": true
            },
            {
              "name": "display_name",
              "required": true
            },
            {
              "name": "id",
              "required": true
            },
            {
              "name": "input_cost",
              "required": true
            },
            {
              "name": "model_id",
              "required": true
            },
            {
              "name": "output_cost",
              "required": true
            },
            {
              "name": "tier",
              "required": true
            }
          ],
          "tier": "secondary"
        },
        {
          "name": "update_template",
          "summary": "Update an existing (non-builtin) workflow template's name/description/content by template_id.",
          "description": "Update an existing (non-builtin) workflow template's name/description/content by template_id. Builtin templates cannot be modified.",
          "params": [
            {
              "name": "content",
              "required": true
            },
            {
              "name": "description",
              "required": true
            },
            {
              "name": "name",
              "required": true
            },
            {
              "name": "template_id",
              "required": true
            }
          ],
          "tier": "secondary"
        }
      ]
    }
  ],
  "note": "GENERATED by `make gen-mcp-docs` (cmd/mcp-tools-export) from internal/mcphost — do not edit by hand.",
  "secondary_total": 49,
  "total": 87
};
