package cli

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"strings"

	"github.com/oopslink/agent-center/internal/workforce"
	wfservice "github.com/oopslink/agent-center/internal/workforce/service"
)

// ProjectCommands returns the `project` subcommand tree.
//
// v2.5.5 (task #59): `project add` no longer takes a slug arg — the
// id is server-generated (`proj-<8hex>`). --kind / --default-agent-cli
// flags are gone alongside the dropped ProjectKind type; --tags
// accepts a comma-separated list of free-text labels.
func (a *App) ProjectCommands() []*Command {
	return []*Command{
		{Name: "add", Summary: "Add a project", Flags: a.projectAddHandler},
		{Name: "list", Summary: "List projects", Flags: a.projectListHandler},
		{Name: "show", Summary: "Show a project", Flags: a.projectShowHandler},
		{Name: "update", Summary: "Update a project", Flags: a.projectUpdateHandler},
		{Name: "remove", Summary: "Remove a project", Flags: a.projectRemoveHandler},
	}
}

func (a *App) projectAddHandler(fs *flag.FlagSet) Handler {
	name := fs.String("name", "", "human-readable name (required)")
	desc := fs.String("description", "", "description")
	tagsCSV := fs.String("tags", "", "comma-separated tags (e.g. coding,ops)")
	format := fs.String("format", FormatTable, formatFlagHelp())
	return func(ctx context.Context, args []string, out, errw io.Writer) ExitCode {
		nameStr := strings.TrimSpace(*name)
		if nameStr == "" {
			return PrintError(errw, *format, "usage_error", "project add [<id>] --name=...", ExitUsage)
		}
		// v2.5.5: id is server-generated by default. Accept an optional
		// positional id override so scripts that pin a specific id
		// (existing fixtures, predictable smoke-test ids) keep working.
		var overrideID workforce.ProjectID
		if len(args) > 0 {
			overrideID = workforce.ProjectID(args[0])
		}
		tags := parseCSVTags(*tagsCSV)
		var dto ProjectDTO
		if a.Client != nil {
			res, cerr := a.Client.ProjectAdd(ctx, ProjectAddRequest{
				ID:          string(overrideID),
				Name:        nameStr,
				Description: *desc,
				Tags:        tags,
			})
			if cerr != nil {
				return HandleClientError(errw, *format, cerr)
			}
			dto = res.Project
		} else {
			res, err := a.ProjectSvc.Add(ctx, wfservice.AddCommand{
				ID:          overrideID,
				Name:        nameStr,
				Description: *desc,
				Tags:        tags,
				Actor:       a.DefaultActor(),
			})
			if err != nil {
				return HandleDomainError(errw, *format, err)
			}
			dto = projectToDTO(res.Project)
		}
		if *format == "json" {
			b, _ := json.Marshal(projectDTOToMap(dto))
			writeOut(out, string(b))
		} else {
			fmt.Fprintf(out, "added project %s\n", dto.ID)
		}
		return ExitOK
	}
}

func (a *App) projectListHandler(fs *flag.FlagSet) Handler {
	format := fs.String("format", FormatTable, formatFlagHelp())
	return func(ctx context.Context, args []string, out, errw io.Writer) ExitCode {
		var dtos []ProjectDTO
		if a.Client != nil {
			var err error
			dtos, err = a.Client.ProjectFindAll(ctx, "")
			if err != nil {
				return HandleClientError(errw, *format, err)
			}
		} else {
			projects, err := a.ProjectRepo.FindAll(ctx, workforce.ProjectFilter{})
			if err != nil {
				return HandleDomainError(errw, *format, err)
			}
			dtos = projectsToDTOs(projects)
		}
		if *format == "json" {
			arr := make([]map[string]any, len(dtos))
			for i, p := range dtos {
				arr[i] = projectDTOToMap(p)
			}
			b, _ := json.Marshal(arr)
			writeOut(out, string(b))
		} else {
			fmt.Fprintf(out, "%-20s %-32s %s\n", "ID", "NAME", "TAGS")
			for _, p := range dtos {
				fmt.Fprintf(out, "%-20s %-32s %s\n", p.ID, p.Name, strings.Join(p.Tags, ","))
			}
		}
		return ExitOK
	}
}

func (a *App) projectShowHandler(fs *flag.FlagSet) Handler {
	format := fs.String("format", FormatTable, formatFlagHelp())
	return func(ctx context.Context, args []string, out, errw io.Writer) ExitCode {
		if len(args) < 1 {
			return PrintError(errw, *format, "usage_error", "project show <id>", ExitUsage)
		}
		var dto ProjectDTO
		if a.Client != nil {
			var err error
			dto, err = a.Client.ProjectFindByID(ctx, args[0])
			if err != nil {
				return HandleClientError(errw, *format, err)
			}
		} else {
			p, err := a.ProjectRepo.FindByID(ctx, workforce.ProjectID(args[0]))
			if err != nil {
				return HandleDomainError(errw, *format, err)
			}
			dto = projectToDTO(p)
		}
		if *format == "json" {
			b, _ := json.Marshal(projectDTOToMap(dto))
			writeOut(out, string(b))
		} else {
			fmt.Fprintf(out, "Project %s\n  name: %s\n  tags: %s\n  version: %d\n",
				dto.ID, dto.Name, strings.Join(dto.Tags, ","), dto.Version)
		}
		return ExitOK
	}
}

func (a *App) projectUpdateHandler(fs *flag.FlagSet) Handler {
	name := fs.String("name", "", "new name")
	desc := fs.String("description", "", "new description")
	tagsCSV := fs.String("tags", "", "new comma-separated tags (replaces existing)")
	versionFlag := fs.Int("version", 0, "expected version (CAS)")
	format := fs.String("format", FormatTable, formatFlagHelp())
	return func(ctx context.Context, args []string, out, errw io.Writer) ExitCode {
		if len(args) < 1 {
			return PrintError(errw, *format, "usage_error", "project update <id>", ExitUsage)
		}
		if *versionFlag <= 0 {
			return PrintError(errw, *format, "usage_error", "--version required for CAS", ExitUsage)
		}
		hasName := isFlagSet(fs, "name")
		hasDesc := isFlagSet(fs, "description")
		hasTags := isFlagSet(fs, "tags")
		if !hasName && !hasDesc && !hasTags {
			return PrintError(errw, *format, "usage_error", "no fields to update", ExitUsage)
		}
		var dto ProjectDTO
		if a.Client != nil {
			req := ProjectUpdateRequest{
				ID:      args[0],
				Version: *versionFlag,
			}
			if hasName {
				req.Name = name
			}
			if hasDesc {
				req.Description = desc
			}
			if hasTags {
				t := parseCSVTags(*tagsCSV)
				req.Tags = &t
			}
			res, cerr := a.Client.ProjectUpdate(ctx, req)
			if cerr != nil {
				return HandleClientError(errw, *format, cerr)
			}
			dto = res.Project
		} else {
			fields := workforce.ProjectUpdateFields{}
			if hasName {
				fields.Name = name
			}
			if hasDesc {
				fields.Description = desc
			}
			if hasTags {
				t := parseCSVTags(*tagsCSV)
				fields.Tags = &t
			}
			if fields.IsEmpty() {
				return PrintError(errw, *format, "usage_error", "no fields to update", ExitUsage)
			}
			res, err := a.ProjectSvc.Update(ctx, wfservice.UpdateCommand{
				ID:      workforce.ProjectID(args[0]),
				Version: *versionFlag,
				Fields:  fields,
				Actor:   a.DefaultActor(),
			})
			if err != nil {
				return HandleDomainError(errw, *format, err)
			}
			dto = projectToDTO(res.Project)
		}
		if *format == "json" {
			b, _ := json.Marshal(projectDTOToMap(dto))
			writeOut(out, string(b))
		} else {
			fmt.Fprintf(out, "updated project %s (version=%d)\n", dto.ID, dto.Version)
		}
		return ExitOK
	}
}

func (a *App) projectRemoveHandler(fs *flag.FlagSet) Handler {
	format := fs.String("format", FormatTable, formatFlagHelp())
	return func(ctx context.Context, args []string, out, errw io.Writer) ExitCode {
		if len(args) < 1 {
			return PrintError(errw, *format, "usage_error", "project remove <id>", ExitUsage)
		}
		if a.Client != nil {
			if _, cerr := a.Client.ProjectRemove(ctx, ProjectRemoveRequest{ID: args[0]}); cerr != nil {
				return HandleClientError(errw, *format, cerr)
			}
		} else {
			_, err := a.ProjectSvc.Remove(ctx, wfservice.RemoveCommand{
				ID:    workforce.ProjectID(args[0]),
				Actor: a.DefaultActor(),
			})
			if err != nil {
				return HandleDomainError(errw, *format, err)
			}
		}
		writeOut(out, fmt.Sprintf("removed project %s", args[0]))
		return ExitOK
	}
}

// projectToMap is the legacy projection helper preserved for tests
// that still produce a domain *workforce.Project.
func projectToMap(p *workforce.Project) map[string]any {
	return projectDTOToMap(projectToDTO(p))
}

// projectDTOToMap renders a ProjectDTO into the canonical JSON map
// shape preserved by the CLI's human/json formatting contract. We keep
// the legacy `project_id` key (not `id`) for backward compatibility
// with existing CLI consumers.
func projectDTOToMap(p ProjectDTO) map[string]any {
	tags := p.Tags
	if tags == nil {
		tags = []string{}
	}
	return map[string]any{
		"project_id":  p.ID,
		"name":        p.Name,
		"description": p.Description,
		"tags":        tags,
		"version":     p.Version,
	}
}

func projectToDTO(p *workforce.Project) ProjectDTO {
	return ProjectDTO{
		ID:          string(p.ID()),
		Name:        p.Name(),
		Description: p.Description(),
		Tags:        p.Tags(),
		Version:     p.Version(),
	}
}

func projectsToDTOs(ps []*workforce.Project) []ProjectDTO {
	out := make([]ProjectDTO, len(ps))
	for i, p := range ps {
		out[i] = projectToDTO(p)
	}
	return out
}

func isFlagSet(fs *flag.FlagSet, name string) bool {
	set := false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == name {
			set = true
		}
	})
	return set
}

// parseCSVTags splits a comma-separated tag list and trims each entry;
// empty entries are dropped. Used by `project add` / `project update`
// CLI flags where the operator passes `--tags=coding,ops`.
func parseCSVTags(s string) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}
