package workforce

import (
	"crypto/rand"
	"errors"
	"fmt"
	"strings"
	"time"
)

// Project is the Workforce BC AR (workforce/02-project).
//
// v2.5.5 (task #59) simplified the model: id is server-generated
// (`proj-<8hex>`), the open-set `kind` enum and per-project
// `default_agent_cli` were dropped, and a free-text `tags` list
// replaced them. The Web Console offers builtin tag suggestions but
// the server does not validate the tag set.
type Project struct {
	id                  ProjectID
	name                string
	description         string
	tags                []string
	createdByIdentityID string
	createdAt           time.Time
	updatedAt           time.Time
	version             int
}

// NewProjectInput captures the constructor arguments.
type NewProjectInput struct {
	ID                  ProjectID
	Name                string
	Description         string
	Tags                []string
	CreatedByIdentityID string
	CreatedAt           time.Time
}

// NewProject constructs a fresh Project with version=1.
func NewProject(in NewProjectInput) (*Project, error) {
	if err := ValidateProjectID(in.ID); err != nil {
		return nil, err
	}
	if strings.TrimSpace(in.Name) == "" {
		return nil, errors.New("project: name required")
	}
	if strings.TrimSpace(in.CreatedByIdentityID) == "" {
		return nil, errors.New("project: created_by_identity_id required")
	}
	if in.CreatedAt.IsZero() {
		return nil, errors.New("project: created_at required")
	}
	return &Project{
		id:                  in.ID,
		name:                in.Name,
		description:         in.Description,
		tags:                normalizeTags(in.Tags),
		createdByIdentityID: in.CreatedByIdentityID,
		createdAt:           in.CreatedAt.UTC(),
		updatedAt:           in.CreatedAt.UTC(),
		version:             1,
	}, nil
}

// RehydrateProjectInput is for repository round-tripping.
type RehydrateProjectInput struct {
	ID                  ProjectID
	Name                string
	Description         string
	Tags                []string
	CreatedByIdentityID string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Version             int
}

// RehydrateProject reconstructs without re-validating the id (so legacy
// rows surviving a future migration can still round-trip).
func RehydrateProject(in RehydrateProjectInput) (*Project, error) {
	if string(in.ID) == "" {
		return nil, errors.New("project: id required")
	}
	if in.Version < 1 {
		return nil, errors.New("project: version must be >= 1")
	}
	return &Project{
		id:                  in.ID,
		name:                in.Name,
		description:         in.Description,
		tags:                normalizeTags(in.Tags),
		createdByIdentityID: in.CreatedByIdentityID,
		createdAt:           in.CreatedAt.UTC(),
		updatedAt:           in.UpdatedAt.UTC(),
		version:             in.Version,
	}, nil
}

// Getters.

func (p *Project) ID() ProjectID               { return p.id }
func (p *Project) Name() string                { return p.name }
func (p *Project) Description() string         { return p.description }
func (p *Project) Tags() []string              { return append([]string(nil), p.tags...) }
func (p *Project) CreatedByIdentityID() string { return p.createdByIdentityID }
func (p *Project) CreatedAt() time.Time        { return p.createdAt }
func (p *Project) UpdatedAt() time.Time        { return p.updatedAt }
func (p *Project) Version() int                { return p.version }

// ProjectUpdateFields aggregates the legal Update changes
// (workforce/00 § 5.4). v2.5.5 dropped Kind / DefaultAgentCLI and
// added Tags.
type ProjectUpdateFields struct {
	Name        *string
	Description *string
	Tags        *[]string
}

// IsEmpty reports whether no fields are set.
func (u ProjectUpdateFields) IsEmpty() bool {
	return u.Name == nil && u.Description == nil && u.Tags == nil
}

// ApplyAndBumpVersion mutates the project according to fields, bumping
// version and updated_at. Project.id is never touched.
func (p *Project) ApplyAndBumpVersion(fields ProjectUpdateFields, at time.Time) error {
	if fields.IsEmpty() {
		return errors.New("project: update has no field changes")
	}
	if fields.Name != nil {
		if strings.TrimSpace(*fields.Name) == "" {
			return errors.New("project: name cannot be empty")
		}
		p.name = *fields.Name
	}
	if fields.Description != nil {
		p.description = *fields.Description
	}
	if fields.Tags != nil {
		p.tags = normalizeTags(*fields.Tags)
	}
	p.updatedAt = at.UTC()
	p.version++
	return nil
}

// ValidateProjectID is a lightweight shape check.
//
// In production the id is always generated by NewProjectID (which emits
// `proj-<8hex>`), so end-to-end the prefix invariant holds. The
// validator only rejects ids that would break URLs / JSON / SQL keys:
// empty, contains whitespace, or longer than 64 chars. We keep it
// permissive enough for in-process tests to use short fixture ids
// (`p`, `proj-a`, `ac`) without churn.
//
// Pre-v2.5.5 slug-form ids are no longer accepted at the DB layer
// because the 0032 migration wipes the projects table, but the
// validator stays lenient so callers can keep using the same code path
// for fixtures and runtime.
func ValidateProjectID(id ProjectID) error {
	s := string(id)
	if s == "" {
		return fmt.Errorf("%w: id required", ErrProjectInvalidID)
	}
	if len(s) > 64 {
		return fmt.Errorf("%w: id too long (max 64, got %d)", ErrProjectInvalidID, len(s))
	}
	for _, c := range s {
		if c == ' ' || c == '\t' || c == '\n' || c == '\r' {
			return fmt.Errorf("%w: id cannot contain whitespace (got %q)", ErrProjectInvalidID, s)
		}
	}
	return nil
}

// NewProjectID returns a fresh server-generated id of the form
// `proj-<8hex>`. 32 bits of entropy is plenty for a single tenant's
// lifetime of projects (collision probability < 1e-9 after 1000
// creates); shorter than ULID so the id stays readable in URLs and
// CLI output. Mirrors generateWorkerID in webconsole/api/handlers.go.
func NewProjectID() (ProjectID, error) {
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return ProjectID(fmt.Sprintf("proj-%x", b[:])), nil
}

// normalizeTags trims whitespace, drops empty entries, and deduplicates
// preserving first-seen order. Stored canonically so JSON round-trips
// don't drift.
func normalizeTags(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, t := range in {
		t = strings.TrimSpace(t)
		if t == "" {
			continue
		}
		if _, ok := seen[t]; ok {
			continue
		}
		seen[t] = struct{}{}
		out = append(out, t)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
