package agentruntime

// codex_mcp.go — T972: translate the canonical claude mcp_config.runtime.json into the
// codex config.toml [mcp_servers.<name>] stdio-launcher tables codex reads from
// $CODEX_HOME/config.toml. A cli=codex SUPERVISOR thus reaches the SAME agent-center MCP
// host binary + the SAME per-agent AC_MCP_* creds as the claude supervisor — it just
// consumes them via config.toml instead of claude's --mcp-config. (Unlike an EXECUTOR,
// a supervisor is SUPPOSED to carry center creds — it is the party that calls the MCP
// tools; the executor env allowlist that DENIES AC_MCP_* is a different, executor-only
// hardening.) config.toml wiring is the T972 hard point: config-gen correctness is
// unit-locked here; creds actually reaching the host + a real tool call are verified by
// the Accept dual-run (a silently-inert config is the CODEX_HOME / judge-P1 blind spot).

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/oopslink/agent-center/internal/mcphost"
)

// codexMCPConfigTOML translates a canonical mcp_config.runtime.json document
// ({"mcpServers":{<name>:{command,args,env}}}) into codex config.toml content with one
// [mcp_servers.<name>] table per server. Output is DETERMINISTIC (server names + env
// keys sorted) so the generated config is reproducible and testable. An empty/absent
// mcpServers yields a header-only doc (no servers) rather than an error, so a
// no-MCP agent simply gets no [mcp_servers.*] tables.
func codexMCPConfigTOML(runtimeJSON []byte) ([]byte, error) {
	var cfg mcphost.MCPConfig
	if err := json.Unmarshal(runtimeJSON, &cfg); err != nil {
		return nil, fmt.Errorf("codex mcp: parse runtime.json: %w", err)
	}
	names := make([]string, 0, len(cfg.MCPServers))
	for name := range cfg.MCPServers {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by agent-center (T972): codex MCP servers, translated from\n")
	b.WriteString("# the canonical mcp_config.runtime.json. Do not edit by hand.\n")
	for _, name := range names {
		s := cfg.MCPServers[name]
		fmt.Fprintf(&b, "\n[mcp_servers.%s]\n", tomlKey(name))
		fmt.Fprintf(&b, "command = %s\n", tomlString(s.Command))
		b.WriteString("args = [")
		for i, a := range s.Args {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(tomlString(a))
		}
		b.WriteString("]\n")
		if len(s.Env) > 0 {
			keys := make([]string, 0, len(s.Env))
			for k := range s.Env {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			b.WriteString("env = { ")
			for i, k := range keys {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%s = %s", tomlKey(k), tomlString(s.Env[k]))
			}
			b.WriteString(" }\n")
		}
	}
	return []byte(b.String()), nil
}

// tomlString renders a Go string as a TOML basic string (double-quoted, escaped).
func tomlString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// tomlKey renders a TOML key: a bare key when it matches [A-Za-z0-9_-]+ (the common
// case for server names + AC_MCP_* env keys), else a quoted key.
func tomlKey(k string) string {
	if k == "" {
		return `""`
	}
	for _, r := range k {
		bare := r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '_' || r == '-'
		if !bare {
			return tomlString(k)
		}
	}
	return k
}
