-- 0003_discussion_issues.up.sql
-- v2.7 #131: discussion tables (issues) RETIRED
-- Fresh install is new-model only — these legacy tables are never created
-- (no drop-migration; nothing to drop). This migration is intentionally a
-- no-op, kept for version-number continuity (schema Version stays 46).
