-- 0004_observability_projections.up.sql
-- v2.7 #131: observability task_execution_projections table RETIRED (new model = agent_work_item_projections, mig 0046)
-- Fresh install is new-model only — these legacy tables are never created
-- (no drop-migration; nothing to drop). This migration is intentionally a
-- no-op, kept for version-number continuity (schema Version stays 46).
