-- 0004_observability_projections.down.sql
-- v2.7 #131: task_execution_projections RETIRED — no-op down
-- Fresh install is new-model only — these legacy tables are never created
-- (no drop-migration; nothing to drop). This migration is intentionally a
-- no-op, kept for version-number continuity (schema Version stays 46).
