-- 0010_v2_task_executions_agent_instance.up.sql
-- v2.7 #131: task_executions.agent_instance_id column — task_executions table RETIRED
-- Fresh install is new-model only — these legacy tables are never created
-- (no drop-migration; nothing to drop). This migration is intentionally a
-- no-op, kept for version-number continuity (schema Version stays 46).
