-- 0032_project_model_simplify.up.sql
-- v2.7 #131: workforce projects/mappings/proposals reshape — tables RETIRED
-- Fresh install is new-model only — these legacy tables are never created
-- (no drop-migration; nothing to drop). This migration is intentionally a
-- no-op, kept for version-number continuity (schema Version stays 46).
