ALTER TABLE pm_tasks ADD COLUMN branch TEXT NOT NULL DEFAULT '';
ALTER TABLE pm_tasks ADD COLUMN base TEXT NOT NULL DEFAULT '';
ALTER TABLE pm_tasks ADD COLUMN skip_merge_check INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pm_tasks ADD COLUMN role TEXT NOT NULL DEFAULT '';
